In [2]:
from ipylab import JupyterFrontEnd
from IPython.display import Markdown, display
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os
from rich.console import Console
console = Console(force_jupyter=True)

# Path to all CSVs
folder_path = "strategy_comparision_summary/*.csv"
csv_files = sorted(glob.glob(folder_path))

console.print(f"Found {len(csv_files)} files.")

# %%
for file_path in csv_files:
    file_name = os.path.basename(file_path)
    console.print(f"Processing: {file_name}")
    df = pd.read_csv(file_path)
    profit_row = df.iloc[0, 1:].astype(float)
    top5_periods = profit_row.sort_values(ascending=False).head(5)    
    # print("\nTop 5 periods with highest profit_total_abs:")
    # display(top5_periods)
    selected_columns = ["Unnamed: 0"] + top5_periods.index.tolist()
    detailed_table = df[selected_columns]
    console.print("Detailed metrics for Top 5 periods:")
    display(detailed_table)

Found 3 files.

Processing: 28072025-0021.csv

Detailed metrics for Top 5 periods:

,Unnamed: 0,humble-insect,free-egret,crisp-molly,star-donkey,heroic-clam
0,profit_total_abs,1287.8756030499999,1085.8367691400001,1069.41066514,1002.83239905,985.8741630399999
1,train_period_days,150,150,150,60,360
2,backtest_timerange,20240101-20250101,20240101-20250101,20240101-20250101,20240101-20250101,20240101-20250101
3,backtest_period_days,270,330,300,180,90
4,test_size,0.2,0.2,0.2,0.7,0.1
5,key,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi
6,trades,278,240,269,265,361
7,profit_mean,0.09285411698146959,0.09082314200842839,0.0797179175246101,0.07594136036525656,0.05468540599763646
8,profit_sum,25.813444520848545,21.797554082022813,21.444119814120118,20.124460496792988,19.741431565146762
9,profit_total,6.439378015249999,5.429183845700001,5.3470533257,5.01416199525,4.9293708151999995
10,duration_avg,18:33:00,18:41:00,18:38:00,18:44:00,18:15:00
11,wins,164,138,157,136,207
12,draws,0,0,0,0,0
13,losses,114,102,112,129,154
14,winrate,0.5899280575539568,0.575,0.5836431226765799,0.5132075471698113,0.5734072022160664
15,cagr,6.3986993406840895,5.39657901150346,5.315086840623081,4.984752959128814,4.900605313562369
16,expectancy,4.63264605413669,4.524319871416667,3.975504331375462,3.784273203962263,2.730953360221604
17,expectancy_ratio,0.28249755869052384,0.2948874800725789,0.24100381388058345,0.26985084538548354,0.14601614466673118
18,sortino,4.58404015157758,4.019803066902904,3.6566086277152485,3.8326678211787986,3.1140484535693074
19,sharpe,2.851359440391403,2.46713070253331,2.3840786102115197,2.2838772694616982,2.088084567414811
20,calmar,262.21731832697185,167.72750685034703,165.19019226542403,179.26127791884463,52.628720938749815
21,sqn,3.2703,3.0445,2.7795,2.6826,2.1025
22,profit_factor,1.6888975554032073,1.6938528942884212,1.5788395172667582,1.554344759900412,1.3422845988616232
23,max_drawdown_account,0.12818815469156794,0.16896455290833637,0.16896455290833637,0.14600819078470084,0.4889157422547285
24,max_drawdown_abs,161.406,168.824,168.824,159.313,255.468

Processing: 31072025-1449.csv

Detailed metrics for Top 5 periods:

,Unnamed: 0,fine-hornet,major-boa,flying-ant,civil-ewe,on-elk
0,profit_total_abs,993.7887271900001,874.66761811,791.9000343900001,780.1813936000001,752.25364504
1,train_period_days,150,120,180,120,120
2,backtest_timerange,20240601-20250101,20240601-20250101,20240601-20250101,20240601-20250101,20240601-20250101
3,backtest_period_days,60,120,30,150,90
4,test_size,0.2,0.6,0.5,0.5,0.6
5,key,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi
6,trades,246,200,185,194,218
7,profit_mean,0.08107425391768858,0.08777637925507877,0.08586881643295195,0.0806375525071972,0.0691921974439031
8,profit_sum,19.94426646375139,17.555275851015754,15.885731040096111,15.643685186396258,15.083899042770877
9,profit_total,4.9689436359500005,4.37333809055,3.9595001719500003,3.9009069680000006,3.7612682252000003
10,duration_avg,18:43:00,18:42:00,18:32:00,19:00:00,18:37:00
11,wins,133,121,109,112,122
12,draws,0,0,0,0,0
13,losses,113,79,76,82,96
14,winrate,0.540650406504065,0.605,0.5891891891891892,0.5773195876288659,0.5596330275229358
15,cagr,20.05603236286474,16.59988829632962,14.351262508447205,14.04321590373794,13.319531713475055
16,expectancy,4.039791573943088,4.373338090550002,4.280540726432436,4.0215535752577285,3.450704793761468
17,expectancy_ratio,0.27215170564804403,0.2603644739979223,0.2541275037425259,0.25213002324814204,0.2167804490921743
18,sortino,6.378344562804579,5.026054069307718,4.814593778551674,4.745454166184537,4.568178819794155
19,sharpe,3.8071996576589995,3.4271971762236073,2.994472832156186,3.0419851972759466,2.9133233446162192
20,calmar,271.32802182493447,171.58529830911982,138.66727241006703,155.48630191184387,176.08065373784316
21,sqn,2.7134,2.7077,2.4594,2.4401,2.2051
22,profit_factor,1.5924718547736183,1.659150567083348,1.618599844636412,1.5965027379285315,1.4922722698134792
23,max_drawdown_account,0.16349409845329327,0.2275441305845713,0.2549171485990125,0.22397838946442397,0.1907020326167488
24,max_drawdown_abs,158.761,149.327,184.833,165.589,174.469

Processing: 31072025-1619.csv

Detailed metrics for Top 5 periods:

,Unnamed: 0,holy-goat,ace-hermit,light-rat,set-viper,prompt-swine
0,profit_total_abs,1164.3398843500001,1153.5844631999998,935.3134872900002,868.5811277300002,832.18496194
1,train_period_days,30,60,60,60,60
2,backtest_timerange,20220601-20250101,20220601-20250101,20220601-20250101,20220601-20250101,20220601-20250101
3,backtest_period_days,180,60,90,120,150
4,test_size,0.1,0.6,0.4,0.4,0.6
5,key,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi,AwesomeMacdFreqAi
6,trades,1043,744,912,774,886
7,profit_mean,0.022390480206689482,0.031065986062619087,0.020546337417151218,0.022515628393396995,0.018801999076582726
8,profit_sum,23.35327085557713,23.1130936305886,18.73825972444191,17.427096376489274,16.658571181852295
9,profit_total,5.821699421750001,5.767922315999999,4.676567436450001,4.3429056386500005,4.1609248097
10,duration_avg,18:27:00,18:28:00,18:34:00,18:41:00,18:35:00
11,wins,570,391,493,433,479
12,draws,0,0,0,0,0
13,losses,473,353,419,341,407
14,winrate,0.5465004793863855,0.5255376344086021,0.5405701754385965,0.5594315245478036,0.5406320541760722
15,cagr,1.0993531142882644,1.0929453690392124,0.9555127571979121,0.9102897598063209,0.8848912369293189
16,expectancy,1.11633737713327,1.5505167516129017,1.0255630343092115,1.1221978394444445,0.9392606793905189
17,expectancy_ratio,0.06397461499891022,0.097043687965364,0.06018515718404038,0.06537959208107402,0.05600854270368294
18,sortino,1.481807999144528,1.4800054377129936,1.1818498155496964,1.0938526670496755,1.0379927086507226
19,sharpe,1.0171518494272325,1.0134075486679173,0.8208547208021828,0.77958769593711,0.7385444309534488
20,calmar,22.115083694602163,64.91815824031468,15.18102617715041,13.73183431331629,28.975259820047018
21,sqn,1.5571,1.8365,1.3437,1.3852,1.2266
22,profit_factor,1.1410687599236011,1.2045340052301157,1.130999673870751,1.1483982529934056,1.1219252305539633
23,max_drawdown_account,0.5322011580037658,0.1796254363271845,0.6227886595960861,0.6393909167123364,0.29032013201582935
24,max_drawdown_abs,645.69,250.66,575.449,631.257,415.449